<?php

/**
 * @file
 * Contains bootcamp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bootcamp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bootcamp module.
    case 'help.page.bootcamp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My bootcamp module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bootcamp_theme() {
  return [
    'bootcamp' => [
      'template' => 'bootcamp',
      'render element' => 'children',
    ],
  ];
}
